name: Test for deploy

on:
  push:
    branches: [ "main" ]

jobs:

  Component-test:

    runs-on: ubuntu-latest
    env:
      REACT_APP_API_ADDRESS: ${{secrets.COMPONENT_TEST_SERVER}}

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "fe-one-source-v3" #Must be unique in Heroku
        heroku_email: "isabelle.annie.karlsson@gmail.com"

  Integration-test:
    needs: Component-test

    runs-on: ubuntu-latest
    env:
      REACT_APP_API_ADDRESS: ${{secrets.INTEGRATION_TEST_SERVER}}

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - uses: cypress-io/github-action@v4.2.0 # use the explicit version number
      with:
        start: npm start
        wait-on: http://localhost:3000
        wait-on-timeout: 120
        browser: chrome
    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "one-source-integration-app" #Must be unique in Heroku
        heroku_email: "anna.toll@protonmail.com"
    - uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: .
